/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d1e567d0e8b622e6162666b
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { EncuestaService } from '../../services/encuesta.service';
import { MateriaService } from '../../services/materia.service';
// Import Models
import { Encuesta } from '../../domain/evaluacion_db/encuesta';

// START - USED SERVICES
/**
* encuestaService.create
*	@description CRUD ACTION create
*
* encuestaService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* materiaService.list
*	@description CRUD ACTION list
*
* encuestaService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Encuesta
 */
@Component({
    selector: 'app-encuesta-edit',
    templateUrl: 'encuesta-edit.component.html',
    styleUrls: ['encuesta-edit.component.css']
})
export class EncuestaEditComponent implements OnInit {
    item: Encuesta;
    model: Encuesta;
    formValid: Boolean;

    constructor(
    private encuestaService: EncuestaService,
    private materiaService: MateriaService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Encuesta();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.encuestaService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Encuesta
     *
     * @param {boolean} formValid Form validity check
     * @param Encuesta item Encuesta to save
     */
    save(formValid: boolean, item: Encuesta): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.encuestaService.update(item).subscribe(data => this.goBack());
            } else {
                this.encuestaService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



